#+TAGS: blog
#+CATEGORIES: stuff
#+TITLE: Why Blogging Matters
#+AUTHOR: Gregor Riegler
#+EMAIL: gregor.riegler@gmail.com
#+DATE: <2014-02-07 Fre>

There is that fancy phrase "pics or it didn't happen". It's just
claiming evidence for a, more or less, hardly credible experience which has often to do
with some sort of drug abuse. Yes, experience shows it's
sometimes cleverer to do without taking a photo, anyway, it crossed my mind that that phrase might be
applicable not only to excess-like experiences but to... pretty much
everything in life.
<!-- more -->

I'll come back later to what that actually means.. actually, I've just found a nice [[http://mdswanson.com/blog/2013/08/11/write-things-tell-people.html][blog post]]
about the importance of running a blog as a developer which goes
nicely with what I've been thinking. The author, Matt Swanson, says
"Do things, write about it" and explains how sharing his learning on
his blog has been incredibly rewarding: Firstly, people told him how much they
enjoy reading his posts (those compliments alone may be worth it!) and secondly, he gained reputation by
demonstrating his abilities and initiative. As a result, he somehow became some
sort of a "super hero" in people's minds although his posts are not
exactly rocket-science. Regular posts (content is still king!) and a
pretty straight-forward way of expressing things were enough to raise
his value... the question is: Did Matt just fool his readers? Isn't he a clever guy after all? 

Of course he is "clever". He is "clever" *because* he shares his
projects, learnings and insights on his blog. Being a Software
developer, blogging about your projects is the most efficient way of
gaining an over-all reputation - a manager, who considers hiring you, won't read commit logs of Open Source
Projects where your name might appear but he can enjoy a well-written blog! In fact,
the 'positive' effect on the manager's decision seems inevitable; and that's
where the "pics or it didn't happen" attitude comes into play. In
order to convey your abilities to the manager you need definite proof,
pretty similiar to the situation in court, actually: In the end, the
judge reaches a verdict and *decides what is the truth*. Analogously,
you will always *be* exactly as "clever" as your vis-à-vis, respectively the
readers of your blog, think you are! It goes without saying that you
can replace the word "clever" with whatever other positive quality you'd
like to convey - "competent", "open-minded", "innovative", ..., you
name it.

Funnily enough, you will actually get cleverer when you blog regularly
;-) Strange? Well, first let's get rid of the word "clever" once and
for all, it is somehow inaccurate - what I want to say is: You will
get better at those topics you're blogging about. (And that not only
applies to tech blogs!) The reason for that: The extra thinking
necessary for presenting your work in a nicely structured way on your
blog will actually force you to nicely structure your projects as
well! In addition, your inner urge to at least blog once, twice or X
times a week will actually force you to pursue your projects and
learnings 'cause otherwise you wouldn't have anything to blog about.
As a result, you'll inevitably get better at reasoning and get a
better understanding of your blog posts' topics... briefly, you get
"cleverer"! Isn't that ironic? ;-) 

Anyway, I haven't been able to post regularly in the past, for
whatever reasons. In the end that always led to abandonning my past blogs altogether, so I'm not
quite sure the above argumentation is too believable coming from me,
to be honest. However, for the moment, it is enough motivation for me to try a fresh
start with this blog. After all, it's all about motivation and inspiration.




