#+TAGS: blog
#+CATEGORIES: stuff
#+SIDEBAR: collapse
#+PUBLISH: true
#+TITLE: A fresh start
#+AUTHOR: Gregor Riegler
#+EMAIL: gregor.riegler@gmail.com
#+DATE: 2014-02-06

2014 has just started a month ago and I've painfully realized that I
didn't come up with any New Year's resolutions at that time. There is
no resolution to violate, consequently, no reason to feel bad at all -
so why not start a new blog which I could then feel bad about when I
post nothing for months?! Well, to be serious, that's at least how all
my blogging attempts have ended so far. I definitely don't know if
history will repeat itself again this time. Maybe this post will actually stay the
only post for two months? Any bets? ;-)

Anyway, I better shortly summarize what I plan blogging about. Being a
software developer, tech topics will probably dominate. Still I can't
promise not to rant about some random topic from time to time ;-) As
an Emacs user I might blog about my *Elisp* learning progress or other
stuff like the one and only *org-mode*. Using *Octopress* as my blogging
engine it will be unavoidable to mention it as well, ranging from
plugins and customizations to its philosophy. From time to time I'd also
like talking about my journeys to *Haskell* wonderland and
*Clojure(Script)* development. Or mention some Android apps? There are
enough topics for sure, we'll see if there is enough motivation to
carry on blogging as well ;-)

Let's hope the best!
